# Continuous integration build specification for travis-ci.org

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - time sudo apt-get -qq install cfitsio-dev python-dev swig
  - time ./autogen.sh
  - time ./configure

install:
  - time make

script:
  - time sudo make install
  - time make check
