# Continuous integration build specification for travis-ci.org

language: cpp

compiler:
  - clang
  - gcc

install:
  - time sudo apt-get -qq install cfitsio-dev python-dev swig
  - time ./autogen.sh
  - time ./configure
  - time make
  - time sudo make install

script:
  - time make check
