# Continuous integration build specification for travis-ci.org

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - time sudo apt-get -qq install cfitsio-dev python-dev swig
  - time ./autogen.sh
  - time ./configure

install:
  # Install phase can only take 10 mins, so time out after 9m here
  - time timeout 9m make

script:
  # Finish make in case it timed out before
  - time make
  - time sudo make install
  - time make check
